

services:
  epic-rides_api:
    container_name: epic-rides_api
    restart: always
    image: node:20.10.0
    ports:
      - "4001:3007"
    volumes:
      - ./:/usr/src/epic-rides
    working_dir: /usr/src/epic-rides

    networks:
      - monorepo-network
    
    # FOR PRODUCTION
    command: bash -c "npm install && npm run build && npm run start:prod"

  epic-rides_batch:
    container_name: epic-rides_batch
    restart: unless-stopped
    image: node:20.10.0
    ports:
      - "4002:3008"
    volumes:
      - ./:/usr/src/epic-rides
    working_dir: /usr/src/epic-rides

    networks:
      - monorepo-network
  
    # FOR PRODUCTION
    command: bash -c "rm -rf dist && npm install && npm run build && npm run start:prod:batch"


networks:
  monorepo-network:
    driver: bridge

# epic-rides-next: localhost:4000 <=> container:3000
# epic-rides_api: localhost:4001 <=> container:3007
# epic-rides_batch: localhost:4002 <=> container:3008
